import Head from 'next/head';
import { Inter } from 'next/font/google';
// // import styles from '@/styles/Home.module.css'
import { FiAlertCircle } from "react-icons/fi";
import { MdKeyboardArrowRight, MdKeyboardArrowDown } from "react-icons/md";
import { FiHeart } from "react-icons/fi";
import PropertyCard from '@/components/propertyCard/PropertyCard';
import Property from '@/components/property/Property';
import ImgPopup from '@/components/imgPopup/ImgPopup';
import Img from "../../assets/img-popup.jpeg";
import ImgTwo from "../../assets/img-popup-two.jpeg";
import ImgThree from "../../assets/img-popup-three.jpeg";
import Tab from '@/components/tab/Tab'
import Chart from '@/components/chart/BarChart'
import BarChart from '@/components/chart/BarChart'
import Map from '@/components/map/Map';
import BuyLandCard from '@/components/buyLandCard/BuyLandCard';
import Header from '@/components/header/Header';
import React, { useState } from 'react';
import { list } from '@/components/constants/data';
import LandMap from '@/components/map/LandMap';
import Link from 'next/link';
import { BsSearch, BsStars, BsStickiesFill } from 'react-icons/bs';
import Logo from "../../assets/logo.png";
import Image from 'next/image';
import { SiAdguard } from 'react-icons/si';
import { GiProgression } from "react-icons/gi";
import { SlArrowDown, SlArrowUp } from "react-icons/sl";
import { HiArrowDownCircle, HiArrowUpCircle } from "react-icons/hi2";
import { GoArrowSwitch } from "react-icons/go";
import IconImg from "../../assets/icon.png";
// import Video from "../../public/"
import ReactPlayer from "react-player";
import Plot from "../../assets/plot.png";
import { HiDocumentText } from 'react-icons/hi';
import { IoIosArrowDown } from 'react-icons/io';
import Slider from '@/components/slider/Slider';
import SliderTwo from '@/components/slider/SliderTwo';

// import styles from "../styles/swiper-custom.css";
const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  const [open, setOpen] = useState(false);
  const [totalInvestment, setTotalInvestment] = useState(false);
  const [financing, setFinancing] = useState(false);
  const [loan, setLoan] = useState(false);
  const [amortization, setAmortization] = useState(true);
  const [revenue, setRevenue] = useState(false);
  const [expenses, setExpenses] = useState(false);
  const [show, setShow] = useState(false);
  const [basic, setBasic] = useState(false);
  const [onChain, setOnChain] = useState(false);
  const [opreating, setOperating] = useState(false);
  const [pass, setPass] = useState(false);
  const [documents , setDocuments] = useState(false);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link href='https://api.mapbox.com/mapbox-gl-js/v2.8.1/mapbox-gl.css' rel='stylesheet' />
      </Head>

        <div className='bg-[#1a1212]' >
            <Header />
            <div className='grid grid-cols-12 gap-8'>
                <div className=' hidden lg:block md:col-span-3 lg:col-span-2 pt-12'>
                    {
                        list?.map((item) => {
                            return <div className='flex flex-col py-3 text-white rounded-md hover:bg-[rgba(134,177,247,0.5)]'>
                                <Link target='_blank' href={`${item?.route}`}>
                                    <div className='flex ml-12  text-[#d1d5db] gap-x-3 cursor-pointer'>   <p>{item.icon}</p> <p>{item.title}</p></div>
                                </Link>   </div>
                        })
                    }
                </div>
                {
                    show ? <div className='col-span-12 lg:col-span-10'>
                        {/* <LandMap /> */}
                        <Image src={Plot} className='w-[95%] hidden lg:flex' />
                              <div className='grid grid-cols-12  lg:gap-20'>
                     
                            <div className='col-span-12  lg:col-span-8'>
                 
                             <p className='text-4xl py-2 font-medium pl-4 lg:pl-0 text-white'>APN 174-783 Hyderabad ,Telangana</p>
                                {/* <video className='h-[300px] w-full' controls autoPlay>
                                    <source src={'../../assets/video/video'} type="video/mp4" />
                                </video> */}
                                {/* <video
                                    width="100%"
                                    height="auto"
                                    className="z-100"
                                    controls
                                    playing
                                    loop      >
                                    <source src='../../public/assets/video/video.mp4' />
                                </video> */}
                                <Image src={Plot} className='lg:hidden flex' />
                                <div>
                                    <div className='bg-[#272626] text-white px-4 flex items-center gap-x-3 py-5'>
                                        <BsStickiesFill />   <p className='text-2xl'>Description</p>
                                    </div>
                                    <div className='text-white bg-[#131212] py-6 px-11 text-lg'>

                                        Prime Residential Land Plot in Ayyapa Society, Madhapur
                                        Welcome to an exceptional opportunity to own a prime residential land plot nestled in the serene and sought-after neighborhood of Ayyapa Society, Madhapur, Hyderabad, India. This meticulously curated plot presents an ideal canvas for your dream home or a lucrative investment in one of the city's most thriving locales.
                                        <br />Location:
                                        The land plot is strategically situated in Ayyapa Society, an upscale and well-established locality known for its tranquil surroundings and excellent connectivity. Its proximity to the bustling IT and financial districts of Madhapur makes it an ideal choice for professionals and families seeking a perfect work-life balance.
                                        <br />Land Area:
                                        Spanning an expansive area of 500 square yards, this generous plot offers ample space to design and construct your dream home, incorporating all the amenities and features you desire.
                                        <br />Land Type:
                                        This plot is categorized as residential, making it an attractive prospect for those looking to build their own customized living space in a well-developed neighborhood.
                                        <br />Ownership:
                                        The land holds a clear and marketable title, offering peace of mind to prospective buyers with a seamless transfer of ownership.
                                        <br />Developments:
                                        The plot is ready for construction, sparing you the hassle of any initial groundwork. Embrace the joy of building a home that perfectly aligns with your vision and lifestyle preferences.
                                        <br />Nearby Amenities:
                                        Residents of Ayyapa Society enjoy easy access to a plethora of amenities, including renowned educational institutions, top-notch healthcare facilities, vibrant shopping centers, and recreational hubs. The area's rich infrastructure and proximity to various entertainment options ensure a convenient and fulfilling lifestyle.
                                        <br />Accessibility:
                                        The plot benefits from excellent transport links and road connectivity, providing smooth commutes to major landmarks and business hubs across Hyderabad.
                                        <br />Investment Potential:
                                        In addition to being an exceptional opportunity for creating a personalized haven, this land plot holds immense investment potential. The thriving real estate market in Madhapur and its proximity to key commercial districts make it a promising asset for long-term growth and appreciation.
                                        Don't miss this chance to be a part of the esteemed Ayyapa Society community, where comfort, convenience, and a vibrant lifestyle converge seamlessly. Embrace the true essence of urban living while being surrounded by green spaces and modern amenities.
                                        8:39
                                        make it so that it expands so it doesn’t show all the text and take up the whole space




                                    </div>
                                </div>
                                <br />
                                <div>
                                    <div className='bg-[#272626] text-white px-4  py-5'>
                                        <div className='flex justify-between'>
                                            <div className='flex items-center gap-x-3'>
                                                <SiAdguard />   <p className='text-2xl'>Confidence Score</p>
                                            </div>
                                            <div className='flex items-center gap-x-2'>
                                                <p className='text-2xl'>1132</p>
                                                <GiProgression fontSize={20} className='text-[#80d0d3]' />
                                            </div>
                                        </div>
                                    </div>
                                    <div className='text-white bg-[#131212] py-6 px-11 text-lg'>
                                        <div onClick={() => setBasic(!basic)} className='bg-[#DEBD6D] my-2 flex justify-between items-center rounded-md py-2 px-4 cursor-pointer' ><p>Basic Validation</p>
                                            <SlArrowUp className={basic ? "rotate-180" : ""} />
                                        </div>
                                        {
                                            basic && <div className='p-3'>
                                                <p className='text-xl py-2'>Is the NFT correctly formed?</p>
                                                <div className='flex items-center gap-x-3 py-1'>
                                                    <HiArrowUpCircle fontSize={24} className='text-[#80d0d3]' />     <p>Token not Burned</p>
                                                </div>
                                                <div className='flex items-center gap-x-3 py-1'>
                                                    <HiArrowUpCircle fontSize={24} className='text-[#80d0d3]' />     <p>Proof of Title Available</p>
                                                </div>       <div className='flex items-center gap-x-3 py-1'>
                                                    <HiArrowUpCircle fontSize={24} className='text-[#80d0d3]' />     <p>GPS Coordinates Are Valid</p>
                                                </div>       <div className='flex items-center gap-x-3 py-1'>
                                                    <HiArrowUpCircle fontSize={24} className='text-[#80d0d3]' />     <p>Holding Entity Declared</p>
                                                </div>       <div className='flex items-center gap-x-3 py-1'>
                                                    <HiArrowUpCircle fontSize={24} className='text-[#80d0d3]' />     <p>Claim Defined in Token Metadata</p>
                                                </div>       <div className='flex items-center gap-x-3 py-1'>
                                                    <HiArrowUpCircle fontSize={24} className='text-[#80d0d3]' />     <p>Operating Agreement Available</p>
                                                </div>    </div>
                                        }

                                        <div onClick={() => setOnChain(!onChain)} className='bg-[#DEBD6D] my-2 flex justify-between items-center rounded-md py-2 px-4 cursor-pointer' ><p>On-Chain history</p>
                                            <SlArrowUp className={onChain ? "rotate-180" : ""} />
                                        </div>
                                        {
                                            onChain && <div className='p-3'>
                                                <p className='text-xl py-2'>Level of confidence in transactions performed on chain</p>
                                                <div className='flex items-center gap-x-3 py-1'>
                                                    <HiArrowUpCircle fontSize={24} className='text-[#80d0d3]' />     <p>All Tranfers KYC'd</p>
                                                </div>
                                                <div className='flex items-center gap-x-3 py-1'>
                                                    <HiArrowUpCircle fontSize={24} className='text-[#80d0d3]' />     <p>Current Owners KYC'd</p>
                                                </div>       <div className='flex items-center gap-x-3 py-1'>
                                                    <HiArrowUpCircle fontSize={24} className='text-[#80d0d3]' />     <p>Current Owners Not in Darklist</p>
                                                </div>
                                            </div>
                                        }

                                        <div onClick={() => setOperating(!opreating)} className='bg-[#DEBD6D] my-2 flex justify-between items-center rounded-md py-2 px-4 cursor-pointer' ><p>Operating-Agreement Level</p>
                                            <SlArrowUp className={opreating ? "rotate-180" : ""} />
                                        </div>
                                        {
                                            opreating && <div className='p-3'>
                                                <p className='text-xl py-2'>Level of features enabled by the legal instrument used</p>
                                                <div className='flex items-center gap-x-3 py-1'>
                                                    <HiArrowUpCircle fontSize={24} className='text-[#80d0d3]' />
                                                    <p>Under a v3.x Operating Agreement</p>
                                                </div>

                                            </div>
                                        }

                                        <div onClick={() => setPass(!pass)} className='bg-[#DEBD6D] my-2 flex justify-between items-center rounded-md py-2 px-4 cursor-pointer' ><p>Pass Title and Load</p>
                                            <SlArrowUp className={pass ? "rotate-180" : ""} />
                                        </div>
                                        {
                                            pass && <div className='p-3'>
                                                <p className='text-xl py-2'>Level of confidence on title history up to and after tokenization</p>
                                                <div className='flex items-center gap-x-3 py-1'>
                                                    <HiArrowUpCircle fontSize={24} className='text-[#80d0d3]' />     <p>Proof of Title Verified</p>
                                                </div>
                                                <div className='flex items-center gap-x-3 py-1'>
                                                    <HiArrowDownCircle fontSize={24} className='text-[#ea4646]' />     <p>Claim in Token Matches Legal Description from County</p>
                                                </div>       <div className='flex items-center gap-x-3 py-1'>
                                                    <HiArrowDownCircle fontSize={24} className='text-[#ea4646]' />     <p>Holding Entity Matches Owner from County Assessor</p>
                                                </div>
                                            </div>
                                        }

                                    </div>


                                </div>
                                <br />
                                <div>
                                    <div className='bg-[#272626] text-white px-4 flex items-center gap-x-3 py-5'>
                                        <GoArrowSwitch fontSize={20} />   <p className='text-2xl'>Property History</p>
                                    </div>
                                    <div className='bg-[#131212] py-6 px-11 '>
                                        <div className='flex items-center my-4 gap-x-3'>
                                            <Image src={IconImg} className='rounded-full' />
                                            <div className='text-white'>
                                                <p className='text-md'>APN 174-783 Hyderabad ,Telangana was on-ramped to aasthi.ai 6 months ago</p>
                                            </div>
                                        </div>

                                    </div>
                                </div>

                            </div>
                            <div className='col-span-12 lg:col-span-4 lg:mr-16  flex flex-col items-center'>
                                <div className='bg-[#131212] w-[100%] flex flex-col py-4 lg:mt-14  justify-center items-center'>
                                    <Image src={Logo} className='rounded-full w-28 h-28' />
                                    <p className='text-[#DEBD6D] font-bold text-2xl py-2'>aasthi.ai</p>
                                    <button className='rounded-md bg-[#DEBD6D] text-white py-2 px-6'>1,217,528 USD
                                        <br />
                                        10 Cr INR</button>
                                    <button className='bg-[#DEBD6D] my-1 flex items-center gap-x-3 rounded-md text-white py-2 px-6'>
                                        <BsStars fontSize={18} />  Buy Shares
                                    </button>
                                </div>

                                <br />
                                <div className='w-full'>
                                    <div className='bg-[#272626]  text-white px-4 flex items-center gap-x-3 py-5'>
                                        <BsSearch fontSize={20} />   <p className='text-2xl'>Details</p>
                                    </div>
                                    <div className='bg-[#131212] py-6 px-11 '>
                                        <div className='flex items-center my-4 gap-x-3'>
                                            <div className='text-white'>
                                                <p className='text-md text-gray-400'>Plot Area:</p>

                                                <li className='py-1'>5000 (sq yds)</li>
                                                <p className='text-md text-gray-400'>Dimensions(L X B):</p>

                                                <li className='py-1'>50 X 100</li>
                                                <p className='text-md text-gray-400'>
                                                    No Of Open Sides:
                                                </p>
                                                <li className='py-1'>2</li>
                                                <p className='text-md text-gray-400'>
                                                    Any Construction Done:
                                                </p>
                                                <li className='py-1'>No</li>
                                                <p className='text-md text-gray-400'>
                                                    Type Of Ownership:
                                                </p>
                                                <li className='py-1'>Freehold</li>
                                                <p className='text-md text-gray-400'>

                                                    Overlooking:
                                                </p>

                                                <li className='py-1'>Garden/Park, Main Road</li>
                                                <p className='text-md text-gray-400'>
                                                    Transaction Type:</p>
                                                <li className='py-1'>

                                                    New Property
                                                </li>
                                            </div>
                                        </div>

                                    </div>
                                </div>


                                <br />
                                <div className='w-full'>
                                    <div className='bg-[#272626]  text-white px-4 flex items-center gap-x-3 py-5'>
                                        <HiDocumentText fontSize={20} />   <p className='text-2xl'>Legals</p>
                                    </div>
                                    <div className='bg-[#131212] py-6 px-11 '>
                                        <div className='flex items-center my-4 gap-x-3'>
                                            <div className='text-white'>
                                                <p className='text-md text-gray-400'>DESCRIPTION</p>

                                                <p className='py-1 font-semibold'>Madhapur Land plot
                                                   
                                                    </p>
                                                    <p className='text-md text-gray-400'>HOLDING</p>
                                                     <p className='py-1'>Aasthi EYD4REH05G3NV Trust</p>
                                            </div>
                                           
                                        </div>
                                        <button onClick={()=> setDocuments(!documents)} className='w-44 bg-[#DeBD6D] flex items-center gap-x-2 justify-center rounded-md text-white px-6 py-2' >Documents
                                        <IoIosArrowDown fontSize={20} />
                                        </button>
                                        {
                                            documents && <div className='absolute mt-2 w-44 bg-white rounded-md py-4 '>
                                       <p onClick={()=> setDocuments(!documents)} className='py-1.5 px-2 cursor-pointer hover:bg-slate-200'>Operating Agreement</p>
                                       <p onClick={()=> setDocuments(!documents)} className='py-1.5 cursor-pointer px-2 hover:bg-slate-200'>Proof of Title</p>
                                            </div>
                                        }
                                    </div>
                                 
                                </div>
                            </div>
                               <SliderTwo />

                        </div>
                    </div>
                        : <div className='col-span-12 lg:col-span-10 pt-16'>
                            <div className='lg:mr-16'>
                                <LandMap />
                            </div>
                            <div className='flex flex-col lg:justify-start justify-center lg:items-start items-center'>
                                <div onClick={() => setShow(!show)}>
                                    <BuyLandCard />
                                </div>
                            </div>
                        </div>
                }
                <br />
            </div>
        </div>
      {/* <div className='mx-4  md:w-9/12 md:mx-auto'>
        <div className='grid gap-4 mt-6 grid-cols-2'>
          <Image onClick={() => setOpen(!open)} src={Img} className="cursor-pointer h-full rounded-[1rem]" />
          <div>
            <Image src={ImgTwo} className="cursor-pointer md:h-64 rounded-[1rem]" />
            <br />
            <Image src={ImgThree} className="cursor-pointer md:h-64 rounded-[1rem]" />
          </div>

        </div>
        {
          open && <ImgPopup open={open} setOpen={setOpen} />

        }


        <div className='flex items-center justify-between'>
          <div>
            <div className='flex gap-2 mt-3 items-center'>
              <p className='font-bold text-[#333333] text-[1.5rem] md:text-[2.25rem]'>$1,295,000</p>
              <p className='bg-[#5FC65F] font-bold text-[0.875rem] h-6 px-2 rounded-xl text-white'>For Sale</p>
            </div>
            <p><span className='font-bold'>
            8602 E Thornwood Dr,
Scottsdale, </span> AZ 85251</p>
          </div>
          <div>
            <FiHeart className='text-[#959595] h-6 w-6 md:h-9 md:w-9 ' />
          </div>
        </div>
        <br />
        <hr />
        <div className='flex gap-3 md:gap-14  w-full justify-center py-4 items-center pr-4'>
          <p><span className='font-extrabold'>3</span><span className='pl-1 text-[12px]'>bd</span></p>
          <div className='h-6 w-[2px] bg-[#ececec]'></div>
          <p><span className='font-extrabold'>3</span><span className='pl-1 text-[12px]'>ba</span></p>
          <div className='h-6 w-[2px] bg-[#ececec]'></div>   <p><span className='font-extrabold'>2039</span><span className='pl-1 text-[12px]'>sqft</span></p>
          <div className='h-6 w-[2px] bg-[#ececec]'></div> <p className='text-[1rem]'>Townhome</p>
        </div>
        <hr />
                <br />
        <div className='flex gap-4'>

          <p className='text-[#2e2e2e] pt-2 pb-5'>View property on</p>
          <div className='flex gap-2'>
            <div className='bg-[red] border-[0.5px] border-black text-white h-10 font-bold text-[1.2rem] w-10 rounded-full  flex items-center justify-center'>R</div>
            <div className='bg-[purple] border-[0.5px] border-black text-white h-10 font-bold text-[1.2rem] w-10 rounded-full  flex items-center justify-center'>V</div>
          </div>
        </div>
        <br />
        <p className='font-bold text-[1.5rem] leading-[2rem] text-[#200955]'>Revenue Projection</p>
        <BarChart />
        <p className='text-center text-[#a9a9a9]'>Seasonalized based on a market RevPAN of $220</p>
        <br />
        <br />
        <div className='grid grid-cols-2 md:grid-cols-4 gap-2'>
          <div className='border-l-[4px] pl-3'>
            <div className='flex gap-1 items-center'>
              <p className='text-[1.125rem] leading-[1.75rem] text-[#a0a0a0]'>Revenue</p>
              <FiAlertCircle className='text-[#a0a0a0] -mt-1' />
            </div>
            <p className='text-[#200955]'><span className='font-bold text-[1.5rem] leading-[2rem]'>$4,806</span>/mo</p>
          </div>
          <div className='border-l-[4px] pl-3'>
            <div className='flex gap-1 items-center'>
              <p className='text-[1.125rem] leading-[1.75rem] text-[#a0a0a0]'>Cap Rate</p>
              <FiAlertCircle className='text-[#a0a0a0] -mt-1 cursor-pointer' />
            </div>

            <p className='text-[#200955]'><span className='font-bold text-[1.5rem] leading-[2rem]'>11.5%</span></p>
          </div>
          <div className='border-l-[4px] pl-3'>
            <div className='flex gap-1 items-center'>
              <p className='text-[1.125rem] leading-[1.75rem] text-[#a0a0a0]'>Gross Yeild</p>
              <FiAlertCircle className='text-[#a0a0a0] -mt-1 cursor-pointer' />
            </div>

            <p className='text-[#200955]'><span className='font-bold text-[1.5rem] leading-[2rem]'>10.5%</span></p>
          </div>
          <div className='border-l-[4px] ]  pl-3'>
            <div className='flex gap-1 items-center'>
              <p className='text-[1.125rem] leading-[1.75rem] text-[#a0a0a0]'>Cash on Cash</p>
              <FiAlertCircle className='text-[#a0a0a0] -mt-1 cursor-pointer' />
            </div>


            <p className='text-[#200955]'><span className='font-bold text-[1.5rem] leading-[2rem]'>14.4%</span></p>
          </div>
        </div>


        <br /> <br />
        <br />  <div className='border-[1px] rounded-[5px] ' >
          <div className='flex px-4 py-4 justify-between'>
            <p className='font-bold text-[1.5rem] leading-[2rem] text-[#200955]'>Calculator</p>
            <button className='border-[1px] rounded-[5px] py-1 px-4'>Edit Preference</button>

          </div>
          <hr />
          <br />
          <div className='flex justify-evenly'>
            <div className='flex flex-col items-center'>
              <p className='text-[1.125rem] leading-[1.75rem] text-[#a0a0a0]'>Cape Rate</p>
              <p className='text-[#200955]'><span className='font-bold text-[1.1rem] leading-[2rem]'>12.1%</span></p>
            </div>
            <div className='flex flex-col items-center'>
              <p className='text-[1.125rem] leading-[1.75rem] text-[#a0a0a0]'>Gross Yeild</p>
              <p className='text-[#200955]'><span className='font-bold text-[1.1rem] leading-[2rem]'>16.7%</span></p>
            </div>
            <div className='flex flex-col items-center'>
              <p className='text-[1.125rem] leading-[1.75rem] text-[#a0a0a0]'>Revenue</p>
              <p className='text-[#200955]'><span className='font-bold text-[1.1rem] leading-[2rem]'>17.6%</span></p>
            </div>
          </div>
          <br />
          <hr />

          <div onClick={() => setTotalInvestment(!totalInvestment)} className='flex cursor-pointer justify-between items-center px-4 py-2'>
            <p className='text-[#200955] font-bold text-[1.1rem] leading-[2rem]'>Total Investment</p>
            <div className='flex gap-0 text-[#232323] font-bold items-center'>
              <p>$530,298</p>
              {
                totalInvestment ? <MdKeyboardArrowDown fontSize={20} /> : <MdKeyboardArrowRight fontSize={20} />
              }
            </div>
          </div>
          {
            totalInvestment &&  <>
            <hr /><div className='px-4'>
             
              <div className='grid md:grid-cols-2 gap-x-8 pb-3'>
                <div className='flex w-full flex-col pt-4'>
                  <label className='text-[1.125rem] leading-[1.75rem] text-[#a0a0a0] pb-[0.5px]'>Asking Price</label>
                  <div className='relative '>
                    <p className='absolute left-2 top-1.5 text-[#200955] text-[1.2rem]'>$</p>
                    <input className=' border-[#e5e7eb] border-[1px] rounded-[5px] h-10 outline-none pl-6 w-full' />
                  </div>
                </div>
                <div className='flex w-full flex-col pt-4'>
                  <label className='text-[1.125rem] leading-[1.75rem] text-[#a0a0a0] pb-[0.5px]'>Purchase Price Factor</label>
                  <div className='relative '>
                    <p className='absolute right-2 top-1.5 text-[#200955] text-[1.2rem]'>%</p>
                    <input className=' border-[#e5e7eb] border-[1px] rounded-[5px] h-10 outline-none pl-6 w-full' />
                  </div>
                </div>
                <div className='flex w-full flex-col pt-3'>
                  <label className='text-[1.125rem] leading-[1.75rem] text-[#a0a0a0] pb-[0.5px]'>Purchase Price</label>
                  <div className='relative '>
                    <p className='absolute left-2 top-1.5 text-[#200955] text-[1.2rem]'>$</p>
                    <input className=' border-[#e5e7eb] border-[1px] rounded-[5px] h-10 outline-none pl-6 w-full' />
                  </div>
                </div>            <div className='flex w-full flex-col pt-3'>
                  <div className='flex gap-1 items-center'>
                    <label className='text-[1.125rem] leading-[1.75rem] text-[#a0a0a0] pb-[0.5px]'>Clothing Costs</label>
                    <FiAlertCircle className='text-[#a0a0a0] -mt-1 cursor-pointer' />     </div>
                  <div className='relative '>
                    <p className='absolute right-2 top-1.5 text-[#200955] text-[1.2rem]'>%</p>
                    <input className=' border-[#e5e7eb] border-[1px] rounded-[5px] h-10 outline-none pl-6 w-full' />
                  </div>
                </div>
                <div className='flex w-full flex-col pt-3'>
                  <label className='text-[1.125rem] leading-[1.75rem] text-[#a0a0a0] pb-[0.5px]'>Immediate Repairs</label>
                  <div className='relative '>
                    <p className='absolute left-2 top-1.5 text-[#200955] text-[1.2rem]'>$</p>
                    <input className=' border-[#e5e7eb] border-[1px] rounded-[5px] h-10 outline-none pl-6 w-full' />
                  </div>
                </div>            <div className='flex w-full flex-col pt-3'>
                  <div className='flex items-center gap-1'>
                    <label className='text-[1.125rem] leading-[1.75rem] text-[#a0a0a0] pb-[0.5px]'>Furnishing Costs</label>  <FiAlertCircle className='text-[#a0a0a0] -mt-1 cursor-pointer' />
                  </div>

                  <div className='relative '>

                    <input className=' border-[#e5e7eb] border-[1px] rounded-[5px] h-10 outline-none pl-6 w-full' />
                  </div>
                </div>            <div className='flex w-full flex-col pt-3'>

                  <div className='flex items-center gap-1'>
                    <label className='text-[1.125rem] leading-[1.75rem] text-[#a0a0a0] pb-[0.5px]'>Initial Expenses</label>
                    <FiAlertCircle className='text-[#a0a0a0] -mt-1 cursor-pointer' />
                  </div>

                  <div className='relative '>
                    <p className='absolute left-2 top-1.5  text-[1.2rem]'>$</p>
                    <input className=' border-[#e5e7eb] border-[1px] rounded-[5px] h-10 outline-none pl-6 w-full' />
                  </div>
                </div>
              </div>
            </div>
       </>   }
          <hr />

          <div onClick={() => setFinancing(!financing)} className='flex cursor-pointer justify-between items-center px-4 py-2'>
            <p className='text-[#200955] font-bold text-[1.1rem] leading-[2rem]'>Financing</p>
            <div className='flex gap-0 text-[#232323] font-bold items-center'>
              <p>$527,977/mo</p>
              {
                financing ? <MdKeyboardArrowDown fontSize={20} /> : <MdKeyboardArrowRight fontSize={20} />
              }
            </div>
          </div>
          <hr />
          {financing && <><div className='px-4'>

            <div className='grid md:grid-cols-2 gap-x-8 pb-3'>
              <div>
                <p className='text-[1.125rem] leading-[1.75rem] mt-3 text-[#a0a0a0]'>Financing Method</p>
                <div className='grid grid-cols-2 gap-4'>
                  <button onClick={() => setLoan(0)} className={`h-10 border-[1px] rounded-[5px] text-[1.125rem] leading-[1.75rem] border-solid   ${loan == 0 ? "bg-[#200955] text-white" : "bg-white hover:bg-[#f7f7f7] text-[#200955]"}`}>Loan</button>
                  <button onClick={() => setLoan(1)} className={`h-10 border-[1px] rounded-[5px] text-[1.125rem] leading-[1.75rem] border-solid   ${loan == 1 ? "bg-[#200955] text-white" : "bg-white hover:bg-[#f7f7f7] text-[#200955]"}`}>Cash Only</button>
                </div>
                {
                  loan == 0 && <>
                    <p className='text-[1.125rem] leading-[1.75rem] mt-3 text-[#a0a0a0] pb-[0.5px]'>Loan Amount</p>
                    <div className='relative '>
                      <p className='absolute left-2 top-1.5  text-[1.2rem]'>$</p>
                      <input disabled placeholder='459,400' className='placeholder:text-[#200955] border-[#e5e7eb] border-[1px] rounded-[5px] h-10 outline-none pl-6 w-full' />
                    </div>
                    <div className='flex items-center gap-1 pt-3'>
                      <label className='text-[1.125rem] leading-[1.75rem] text-[#a0a0a0] pb-[0.5px]'>Interest Rate</label>
                      <FiAlertCircle className='text-[#a0a0a0] -mt-1 cursor-pointer' />
                    </div>

                    <div className='relative '>
                      <p className='absolute left-2 top-1.5  text-[1.2rem]'>$</p>
                      <input className=' border-[#e5e7eb] border-[1px] rounded-[5px] h-10 outline-none pl-6 w-full' />
                    </div>
                    {
                      amortization ? <> <div className='flex items-center gap-1 pt-3'>
                        <label className='text-[1.125rem] leading-[1.75rem] text-[#a0a0a0] pb-[0.5px]'>Amortization Term</label>
                        <FiAlertCircle className='text-[#a0a0a0] -mt-1 cursor-pointer' />
                      </div>
                        <div className='relative '>
                          <input className=' border-[#e5e7eb] border-[1px] rounded-[5px] h-10 outline-none pl-6 w-full' />
                        </div>
                      </> : <>
                        <button className='border-[#e5e7eb] border-[1px] rounded-[5px] h-10 text-center w-full mt-6 hover:bg-[#f7f7f7]'>Get a free landing quote</button>
                      </>}
                  </>
                }
              </div>
              <div>

                {
                  loan == 0 ? <>
                    <div className='flex items-center gap-1 pt-3'>
                      <label className='text-[1.125rem] leading-[1.75rem] text-[#a0a0a0] pb-[0.5px]'>Down Payment</label>
                      <FiAlertCircle className='text-[#a0a0a0] -mt-1 cursor-pointer' />
                    </div>

                    <div className='flex justify-between'>
                      <div className='relative w-full '>
                        <p className='absolute left-2 top-1.5  text-[1.2rem]'>$</p>
                        <input className=' border-[#e5e7eb] border-[1px] rounded-l-[5px] h-10 outline-none pl-6 w-full' />
                      </div>
                      <div className='relative w-full '>
                        <p className='absolute right-2 top-1.5  text-[1.2rem]'>%</p>
                        <input className=' border-[#e5e7eb] border-[1px] rounded-r-[5px] h-10 outline-none pl-6 w-full' />
                      </div>
                    </div>
                    <div className='flex items-center gap-1 pt-3'>
                      <label className='text-[1.125rem] leading-[1.75rem] text-[#a0a0a0] pb-[0.5px]'>Loan Closing Costs</label>
                      <FiAlertCircle className='text-[#a0a0a0] -mt-1 cursor-pointer' />
                    </div>

                    <div className='relative '>
                      <p className='absolute right-2 top-1.5  text-[1.2rem]'>%</p>
                      <input className=' border-[#e5e7eb] border-[1px] rounded-[5px] h-10 outline-none pl-6 w-full' />
                    </div>
                    <div className='flex items-center gap-1 pt-3'>
                      <label className='text-[1.125rem] leading-[1.75rem] text-[#a0a0a0] pb-[0.5px]'>Interest Type</label>
                      <FiAlertCircle className='text-[#a0a0a0] -mt-1 cursor-pointer' />
                    </div>
                    <div className='grid grid-cols-2 gap-4'>
                      <button onClick={() => setAmortization(!amortization)} className={`h-10 border-[1px] rounded-[5px] text-[1.125rem] leading-[1.75rem] border-solid   ${amortization ? "bg-[#200955] text-white" : "bg-white hover:bg-[#f7f7f7] text-[#200955]"}`}>Amortization</button>
                      <button onClick={() => setAmortization(!amortization)} className={`h-10 border-[1px] rounded-[5px] text-[1.125rem] leading-[1.75rem] border-solid   ${amortization ? "bg-white hover:bg-[#f7f7f7] text-[#200955]" : "bg-[#200955] text-white "}`}>Interest Only</button>
                    </div>

                  </> : <div className='mt-4'>
                    <button className='border-[#e5e7eb] border-[1px] rounded-[5px] h-10 text-center w-full mt-6 hover:bg-[#f7f7f7]'>Get a free landing quote</button>
                  </div>
                }
              </div>

            </div>

          </div>
            <hr />
          </>}

          <div onClick={() => setRevenue(!revenue)} className='flex cursor-pointer justify-between items-center px-4 py-2'>
            <p className='text-[#200955] font-bold text-[1.1rem] leading-[2rem]'>Revenue</p>
            <div className='flex gap-0 text-[#232323] font-bold items-center'>
              <p>$8,999/mo</p>
              {
                revenue ? <MdKeyboardArrowDown fontSize={20} /> : <MdKeyboardArrowRight fontSize={20} />
              }
            </div>
          </div>
          {
            revenue && <> <hr />
              <div className='px-4 pb-3'>
                <div className='grid md:grid-cols-2 gap-x-8 '>
                  <div>
                    <div className='flex items-center gap-1 pt-3 '>
                      <label className='text-[1.125rem] leading-[1.75rem] text-[#a0a0a0] pb-[0.5px]'>RevPAN</label>
                      <FiAlertCircle className='text-[#a0a0a0] -mt-1 cursor-pointer' />
                    </div>
                    <div className='relative '>
                      <p className='absolute left-2 top-1.5  text-[1.2rem]'>$</p>
                      <input placeholder='459,400' className='placeholder:text-[#200955] border-[#e5e7eb] border-[1px] rounded-[5px] h-10 outline-none pl-6 w-full' />
                    </div>
                    <p className='text-[#a0a0a0] pt-3 text-[0.9rem]'>$230 is the projected RevPan based on comparable Airbnbs for this specific property, according to our Airbnb Calculator.</p>
                    <div className='flex items-center gap-1 pt-3 '>
                      <label className='text-[1.125rem] leading-[1.75rem] text-[#a0a0a0] pb-[0.5px]'>Monthly Revenue</label>
                      <FiAlertCircle className='text-[#a0a0a0] -mt-1 cursor-pointer' />
                    </div>
                    <div className='relative '>
                      <p className='absolute left-2 top-1.5  text-[1.2rem]'>$</p>
                      <input disabled placeholder='459,400' className='placeholder:text-[#200955] border-[#e5e7eb] border-[1px] rounded-[5px] h-10 outline-none pl-6 w-full' />
                    </div>

                  </div>
                  <div>
                    <div className='flex items-center gap-1 pt-3 '>
                      <label className='text-[1.125rem] leading-[1.75rem] text-[#a0a0a0] pb-[0.5px]'>Other Income</label>
                      <FiAlertCircle className='text-[#a0a0a0] -mt-1 cursor-pointer' />
                    </div>
                    <div className='relative '>
                      <p className='absolute left-2 top-1.5  text-[1.2rem]'>$</p>
                      <input placeholder='459,400' className='placeholder:text-[#200955] border-[#e5e7eb] border-[1px] rounded-[5px] h-10 outline-none pl-6 w-full' />
                    </div>
                    <p className='text-[#a0a0a0] pt-3 text-[0.9rem]'>$230 is the projected RevPan based on comparable Airbnbs for this specific property, according to our Airbnb Calculator.</p>
                    <div className='flex items-center gap-1 pt-3 '>
                      <label className='text-[1.125rem] leading-[1.75rem] text-[#a0a0a0] pb-[0.5px]'>Annual Revenue</label>
                      <FiAlertCircle className='text-[#a0a0a0] -mt-1 cursor-pointer' />
                    </div>
                    <div className='relative '>
                      <p className='absolute left-2 top-1.5  text-[1.2rem]'>$</p>
                      <input disabled placeholder='459,400' className='placeholder:text-[#200955] border-[#e5e7eb] border-[1px] rounded-[5px] h-10 outline-none pl-6 w-full' />
                    </div>
                  </div>
                </div>
              </div>
            </>
          }
          <hr />
          <div onClick={() => setExpenses(!expenses)} className='flex cursor-pointer justify-between items-center px-4 py-2'>
            <p className='text-[#200955] font-bold text-[1.1rem] leading-[2rem]'>Expenses</p>
            <div className='flex gap-0 text-[#232323] font-bold items-center'>
              <p>$5,398/mo</p>
              <MdKeyboardArrowRight fontSize={20} />
            </div>
          </div>

          {
            expenses && <>
            <hr />  <div className='px-4'>
         
              <div className='grid md:grid-cols-2 gap-x-8 pb-3'>
                <div className='flex w-full flex-col pt-4'>

                  <div className='flex items-center gap-1  '>
                    <label className='text-[1.125rem] leading-[1.75rem] text-[#a0a0a0] pb-[0.5px]'>Channel Fees</label>
                    <FiAlertCircle className='text-[#a0a0a0] -mt-1 cursor-pointer' />
                  </div>
                  <div className='relative '>
                    <p className='absolute right-2 top-1.5 text-[#200955] text-[1.2rem]'>%</p>
                    <input className=' border-[#e5e7eb] border-[1px] rounded-[5px] h-10 outline-none pl-6 w-full' />
                  </div>
                </div>
                <div className='flex w-full flex-col pt-4'>
                  <div className='flex items-center gap-1 '>
                    <label className='text-[1.125rem] leading-[1.75rem] text-[#a0a0a0] pb-[0.5px]'>Project Management Fee</label>
                    <FiAlertCircle className='text-[#a0a0a0] -mt-1 cursor-pointer' />
                  </div>
                  <div className='relative '>
                    <p className='absolute right-2 top-1.5 text-[#200955] text-[1.2rem]'>%</p>
                    <input className=' border-[#e5e7eb] border-[1px] rounded-[5px] h-10 outline-none pl-6 w-full' />
                  </div>
                </div>
                <div className='flex w-full flex-col pt-3'>
                  <div className='flex items-center gap-1'>
                    <label className='text-[1.125rem] leading-[1.75rem] text-[#a0a0a0] pb-[0.5px]'>Supply Fees</label>
                    <FiAlertCircle className='text-[#a0a0a0] -mt-1 cursor-pointer' />
                  </div>
                  <div className='relative '>
                    <p className='absolute left-2 top-1.5 text-[#200955] text-[1.2rem]'>$</p>
                    <input className=' border-[#e5e7eb] border-[1px] rounded-[5px] h-10 outline-none pl-6 w-full' />
                  </div>
                </div>            <div className='flex w-full flex-col pt-3'>
                  <div className='flex gap-1 items-center'>
                    <label className='text-[1.125rem] leading-[1.75rem] text-[#a0a0a0] pb-[0.5px]'>Property Taxes</label>
                    <FiAlertCircle className='text-[#a0a0a0] -mt-1 cursor-pointer' />     </div>
                  <div className='relative '>
                    <p className='absolute right-2 top-1.5 text-[#200955] text-[1.2rem]'>%</p>
                    <input className=' border-[#e5e7eb] border-[1px] rounded-[5px] h-10 outline-none pl-6 w-full' />
                  </div>
                </div>
                <div className='flex w-full flex-col pt-3'>
                  <div className='flex items-center gap-1'>
                    <label className='text-[1.125rem] leading-[1.75rem] text-[#a0a0a0] pb-[0.5px]'>Insurance</label>
                    <FiAlertCircle className='text-[#a0a0a0] -mt-1 cursor-pointer' />
                  </div>
                  <div className='relative '>
                    <p className='absolute left-2 top-1.5 text-[#200955] text-[1.2rem]'>$</p>
                    <input className=' border-[#e5e7eb] border-[1px] rounded-[5px] h-10 outline-none pl-6 w-full' />
                  </div>
                </div>            <div className='flex w-full flex-col pt-3'>
                  <div className='flex items-center gap-1'>
                    <label className='text-[1.125rem] leading-[1.75rem] text-[#a0a0a0] pb-[0.5px]'>HOA Fees</label>  <FiAlertCircle className='text-[#a0a0a0] -mt-1 cursor-pointer' />
                  </div>

                  <div className='relative '>
                    <input className=' border-[#e5e7eb] border-[1px] rounded-[5px] h-10 outline-none pl-6 w-full' />
                  </div>
                </div>
                <div className='flex w-full flex-col pt-3'>
                  <div className='flex items-center gap-1'>
                    <label className='text-[1.125rem] leading-[1.75rem] text-[#a0a0a0] pb-[0.5px]'>Utilities</label>
                    <FiAlertCircle className='text-[#a0a0a0] -mt-1 cursor-pointer' />
                  </div>
                  <div className='flex justify-between'>
                    <div className='relative w-full '>
                      <p className='absolute left-2 top-1.5  text-[1.2rem]'>$</p>
                      <input className=' border-[#e5e7eb] border-[1px] rounded-l-[5px] h-10 outline-none pl-6 w-full' />
                    </div>
                    <div className='relative w-full '>
                      <p className='absolute right-2 top-1.5  text-[1.2rem]'>%</p>
                      <input className=' border-[#e5e7eb] border-[1px] rounded-r-[5px] h-10 outline-none pl-6 w-full' />
                    </div>
                  </div>
                </div>
                <div className='flex w-full flex-col pt-3'>
                  <div className='flex items-center gap-1'>
                    <label className='text-[1.125rem] leading-[1.75rem] text-[#a0a0a0] pb-[0.5px]'>Maintenance</label>
                    <FiAlertCircle className='text-[#a0a0a0] -mt-1 cursor-pointer' />
                  </div>
                  <div className='relative '>
                    <p className='absolute left-2 top-1.5  text-[1.2rem]'>$</p>
                    <input className=' border-[#e5e7eb] border-[1px] rounded-[5px] h-10 outline-none pl-6 w-full' />
                  </div>
                </div>     <div className='flex w-full flex-col pt-3'>
                  <div className='flex items-center gap-1'>
                    <label className='text-[1.125rem] leading-[1.75rem] text-[#a0a0a0] pb-[0.5px]'>Other Expenses</label>
                    <FiAlertCircle className='text-[#a0a0a0] -mt-1 cursor-pointer' />
                  </div>
                  <div className='flex justify-between'>
                    <div className='relative w-full '>
                      <p className='absolute left-2 top-1.5  text-[1.2rem]'>$</p>
                      <input className=' border-[#e5e7eb] border-[1px] rounded-l-[5px] h-10 outline-none pl-6 w-full' />
                    </div>
                    <div className='relative w-full '>
                      <p className='absolute right-2 top-1.5  text-[1.2rem]'>%</p>
                      <input className=' border-[#e5e7eb] border-[1px] rounded-r-[5px] h-10 outline-none pl-6 w-full' />
                    </div>
                  </div>
                </div>
              </div>
            </div>
            </>    }
<hr />
          <br />
          <div className='flex justify-between items-center px-4 py-2'>
            <div className='flex gap-1 items-center'>
              <p className='text-[#200955] font-bold text-[1.1rem] leading-[2rem]'>Upfront Equity</p>
              <FiAlertCircle className='text-[#a0a0a0] -mt-1' />     </div>
            <div className='flex gap-0 text-[#232323] font-bold items-center'>
              <p>$140,298</p>
              <MdKeyboardArrowRight fontSize={20} />
            </div>
          </div>

          <div className='flex justify-between items-center px-4 py-2'>
            <div className='flex gap-1 items-center'>
              <p className='text-[#200955] font-bold text-[1.1rem] leading-[2rem]'>Net Operating Income</p>
              <FiAlertCircle className='text-[#a0a0a0] -mt-1 cursor-pointer' />
            </div>

            <div className='flex gap-0 text-[#232323] font-bold items-center'>
              <p>$5,308/yr</p>
              <MdKeyboardArrowRight fontSize={20} />
            </div>
          </div>
          <div className='flex justify-between items-center px-4 pt-2 pb-4'>

            <div className='flex gap-1 items-center'>
              <p className='text-[#200955] font-bold text-[1.1rem] leading-[2rem]'>Leveraged Net Cash Flow</p>
              <FiAlertCircle className='text-[#a0a0a0] -mt-1 cursor-pointer' />
            </div>

            <div className='flex gap-0 text-[#232323] font-bold items-center'>
              <p>$5,308/yr</p>
              <MdKeyboardArrowRight fontSize={20} />
            </div>
          </div>
        </div>
        <br />
        <br />
        <p className='font-bold text-[1.5rem] leading-[2rem] text-[#200955]'>Location</p>
        <br />

        <Map />
        <br />
        <br />
        <p className='font-bold text-[1.5rem] leading-[2rem] text-[#200955]'>Market Data</p>
        <p className='text-[#2e2e2e] pt-2 pb-5'>Performance of Airbnbs in the overall market for State College, PA 16803. Data displayed is not impacted by filters in this search.</p>
        <Tab />
        <button className=' w-full text-center border-[1px] rounded-[0.375rem] font-medium text-[1.125rem] text-[#200955] leading-[1.75rem] hover:bg-slate-50 py-1 my-4'>View more market data for State College</button>
        <p className='font-bold text-[1.5rem] leading-[2rem] text-[#200955] py-8'>Nearby Airbnbs</p>

        <div className='grid grid-cols-1 lg:grid-cols-4 gap-4'>
          <Property />
          <Property />
          <Property />
          <Property />
        </div>
        <br />

        <p className='font-bold text-[1.5rem] leading-[2rem] text-[#200955]'>For Sale in Centre County</p>
        <p className='text-[#2e2e2e] pt-2 pb-5'>Nearby properties for sale with positive cash-on-cash returns</p>

        <div className='grid grid-cols-1 lg:grid-cols-3 gap-4'>

          <PropertyCard />
          <PropertyCard />
          <PropertyCard />
        </div>
        <br /><br />
        <div className='bg-[#f8f7f7] rounded-[0.75rem] p-[1rem] md:p-[5rem]'>
          <p className='font-bold text-[1.5rem] leading-[2rem] text-center text-[#200955] pb-10 md:pb-24'>Nearby Airbnbs for sale</p>

          <p className='text-[1.125rem] leading-[1.75rem] cursor-pointer hover:underline'>Centre County Airbnbs For Sale</p>
          <p className='text-[1.125rem] leading-[1.75rem] cursor-pointer hover:underline'>State College Airbnbs For Sale</p>
          <p className='text-[1.125rem] leading-[1.75rem] cursor-pointer hover:underline'>Pennsylvania Airbnbs For Sale</p>
          <p className='text-[1.125rem] leading-[1.75rem] cursor-pointer hover:underline'>16803 Airbnbs For Sale</p>
        </div>
      </div> */}
      
    </>
  )
}



